### ISSUE TITLE
Unhandled Rejection (TypeError): Cannot read property 'process' of undefined

### ISSUE THREAD

**Issue by KonstantinKliukach** [imodeljs/desktop-starter#36]
### Steps to reproduce ###

Everything, like in the [intruction](https://www.imodeljs.org/getting-started/)

1. ```git clone https://github.com/imodeljs/desktop-starter.git```
2. ```npm install```
3. ```npm start```

### Result ###
```
Unhandled Rejection (TypeError): Cannot read property 'process' of undefined
```
![Screenshot](https://user-images.githubusercontent.com/45252894/95558975-b876f600-0a1f-11eb-9d89-f27a7bef7dfb.JPG)

**Comment by calebmshafer** [comment]
@KonstantinKliukach I was able to reproduce this as well. It is due to a change made in iModel.js 2.7.0 that does not allow access to `getRemote()` from the renderer Electron process. This was changed to address security concerns where the frontend code would have access directly to the users desktop.

I'll have a PR later today that should address this and handle it a new more secure way.
